### ISSUE TITLE
pouchdb-find doesnt seem to work with it

### ISSUE THREAD

**Issue by arsy29** [pouchdb-community/pouchdb-adapter-cordova-sqlite#81]
pouchdb-find plugin doesnt seem to work with it. Im currently building a mobile app based on ionic, and been using this plugin to set pouchdb adaptor to sqlite. Using db.find result to empty array even though i know there are currently object that exists in the sqlite since ive tried to use allDocs and manually filter the result using the same criteria. I also tried to mimic it using websql and that seems to work. Im currently using array filtering and would like help since i think this waste too much processing thanks...

**Comment by thorvx** [comment]
same issue

**Comment by paolosanchi** [comment]
Same probleme here, I need more than a 50mb db on IOS, for an app that works offline, and I'm currently using pouchdb-find.
What should I do?
Is there an alternative to this plugin that seems dead?

**Comment by markusdenhoff** [comment]
Are you using Webpack? The change in this PR might help you: https://github.com/pouchdb-community/pouchdb-adapter-cordova-sqlite/pull/79

I’m currently patching  pouchdb-adapter-cordova-sqlite with [patch-package](https://www.npmjs.com/package/patch-package) to get it working until the PR is accepted.

**Comment by paolosanchi** [comment]
I'm using ionc 2 and angular cli. I've already applyed that fix changing the source, it gave no error but an empty array was returned. I'll try to apply the PR with path-package.

**Comment by paolosanchi** [comment]
I finally get it working,
- updated to pouchdb 6.4.3 
- deleted node_module
- npm install
- applyed the patch https://github.com/pouchdb-community/pouchdb-adapter-cordova-sqlite/pull/79
