### ISSUE TITLE
WebSqlPouchCore.call is not a function

### ISSUE THREAD

**Issue by bsuyog16** [pouchdb-community/pouchdb-adapter-cordova-sqlite#82]
I am trying to use cordova sqllite through pouchdb in angular 4 as follows: 

test.ts

```
import PouchDB from "pouchdb";
import cordovaSqlitePlugin from 'pouchdb-adapter-cordova-sqlite';

export class PouchdatabaseProvider {
  public db;
  constructor() {
    PouchDB.plugin(cordovaSqlitePlugin);
    this.db = new PouchDB("myDatabase", {adapter: 'cordova-sqlite'});
  } 
}

```

I am getting error as TypeError: WebSqlPouchCore.call is not a function

I have also followed solution #78. But I am not getting how to use **.default** in ts file.

I am using following versions :
pouchdb: "^6.4.1",
pouchdb-adapter-cordova-sqlite: "^2.0.2",
pouchdb-adapter-websql-core: "6.4.1",

Environment: Node => 8.9.3 , Ionic =>3.19.0
Platform: Android
Adapter: cordova-sqlite
Server: PouchDB

Kindly help.

**Comment by MirkoMignini** [comment]
Hello @bsuyog16 I'm facing the same issue, did you solve? Thanks

**Comment by MirkoMignini** [comment]
Thank you very much @paolosanchi fix #79 solved my issue.

**Comment by paolosanchi** [comment]
waiting the release you can try this:

npm install pouchdb-community/pouchdb-adapter-cordova-sqlite#master --save

**Comment by TDola** [comment]
Any updates on this?  I am using browserify and regular cordova if it matters.

**Comment by TDola** [comment]
@paolosanchi 
I get 

```
Unhandled rejection TypeError: Cannot read property 'call' of undefined
    at PouchDB.CordovaSQLitePouch (file:///android_asset/www/js/vendor.bundle.js:72684:19)
    at new PouchDB (file:///android_asset/www/js/vendor.bundle.js:77203:34)
```
![image](https://user-images.githubusercontent.com/30079906/42242199-b4d72fae-7ed2-11e8-85a3-252efe3bd820.png)

**Comment by paolosanchi** [comment]
I don't know why websql-core is needed, maybe because of utility stuff.. 
I haven't tried with the v7.0.0 but updating pouchdb-adapter-cordova-sqlite to this should work.

    "pouchdb-adapter-cordova-sqlite": "^2.0.3",

let me know if it works for you

**Comment by TDola** [comment]
Sorry that causes a different issue.
Unhandled rejection TypeError: Cannot use 'in' operator to search for 'default' in undefined
    at PouchDB.CordovaSQLitePouch (file:///android_asset/www/js/vendor.bundle.js:72684:18)

Because WebSqlPouchCore is undefined, we can't use `in` on it.

The `var WebSqlPouchCore = require('pouchdb-adapter-websql-core').default` would have to be changed to `var WebSqlPouchCore = require('pouchdb-adapter-websql-core')`

Like this

```
'use strict'

var WebSqlPouchCore = require('pouchdb-adapter-websql-core')
var assign = require('./assign')

/* global cordova, sqlitePlugin, openDatabase */
function createOpenDBFunction (opts) {
  return function (name, version, description, size) {
    if (typeof sqlitePlugin !== 'undefined') {
      // The SQLite Plugin started deviating pretty heavily from the
      // standard openDatabase() function, as they started adding more features.
      // It's better to just use their "new" format and pass in a big ol'
      // options object. Also there are many options here that may come from
      // the PouchDB constructor, so we have to grab those.
      var sqlitePluginOpts = assign({}, opts, {
        name: name,
        version: version,
        description: description,
        size: size
      })
      return sqlitePlugin.openDatabase(sqlitePluginOpts)
    }

    // Traditional WebSQL API
    return openDatabase(name, version, description, size)
  }
}

function CordovaSQLitePouch (opts, callback) {
  var websql = createOpenDBFunction(opts)
  var _opts = assign({
    websql: websql
  }, opts)

  if (typeof cordova === 'undefined' || typeof sqlitePlugin === 'undefined' || typeof openDatabase === 'undefined') {
    console.error(
      'PouchDB error: you must install a SQLite plugin ' +
      'in order for PouchDB to work on this platform. Options:' +
      '\n - https://github.com/nolanlawson/cordova-plugin-sqlite-2' +
      '\n - https://github.com/litehelpers/Cordova-sqlite-storage' +
      '\n - https://github.com/Microsoft/cordova-plugin-websql')
  }

  if ( 'default' in WebSqlPouchCore && typeof WebSqlPouchCore.default.call === 'function') {
    WebSqlPouchCore.default.call(this, _opts, callback)
  } else {
    WebSqlPouchCore.call(this, _opts, callback)
  }
}

CordovaSQLitePouch.valid = function () {
  // if you're using Cordova, we assume you know what you're doing because you control the environment
  return true
}

// no need for a prefix in cordova (i.e. no need for `_pouch_` prefix
CordovaSQLitePouch.use_prefix = false

function cordovaSqlitePlugin (PouchDB) {
  PouchDB.adapter('cordova-sqlite', CordovaSQLitePouch, true)
}

if (typeof window !== 'undefined' && window.PouchDB) {
  window.PouchDB.plugin(cordovaSqlitePlugin)
}

module.exports = cordovaSqlitePlugin
```

I noticed pouchdb-adapter-websql-core has both index.js and index.es.js.  The es version has the export default.  What controls which lib to load? (sorry for my inexperience)

**Comment by TDola** [comment]
Success.

In my fork I also updated the dependencies.  It apparently removed 54 packages in the update.  So probably requires serious testing.  There is a version 7 of pouchdb-adapter-websql-core though so might not need to remove it just yet.

https://github.com/BisonTransport/pouchdb-adapter-cordova-sqlite

```
  "dependencies": {
    "pouchdb-adapter-websql-core": "^7.0.0"
  },
  "devDependencies": {
    "browserify": "^16.2.2",
    "bundle-collapser": "^1.3.0",
    "mkdirp": "^0.5.1",
    "standard": "^11.0.1",
    "uglify-js": "^3.4.3"
  }
```

**Comment by paolosanchi** [comment]
Good, I'll check it out. I'll close all these topics
