### ISSUE TITLE
Release v2.0.3 to npm

### ISSUE THREAD

**Issue by fazpu** [pouchdb-community/pouchdb-adapter-cordova-sqlite#86]
According to npmjs, the lastest release is v2.0.2: https://www.npmjs.com/package/pouchdb-adapter-cordova-sqlite.

I believe the the v2.0.3 contains fix for https://github.com/pouchdb-community/pouchdb-adapter-cordova-sqlite/issues/81

**Comment by paolosanchi** [comment]
Yes, we are waiting for someone with the permissions to do it..
@daleharvey can you help?

**Comment by coderroggie** [comment]
Pinged @daleharvey to see if we can get this pushed. Not sure that he gets pinged on all of these issues.

**Comment by nolanlawson** [comment]
Sorry for the delay. I've added @daleharvey as an npm owner and also gone ahead and published 2.0.3. to npm: https://www.npmjs.com/package/pouchdb-adapter-cordova-sqlite
