### ISSUE TITLE
Release v2.0.5 to npm

### ISSUE THREAD

**Issue by paolosanchi** [pouchdb-community/pouchdb-adapter-cordova-sqlite#89]
I closed the issues related to "winningRev is not a function" and "WebSqlPouchCore.call is not a function" errors.
The v2.0.5 should solve. Can you @daleharvey publish the v2.0.5 to npm?
Thanks

**Comment by jpike88** [comment]
@daleharvey please can this be updated

**Comment by daleharvey** [comment]
@paolosanchi Can you give me your npm username and I can give you permission to publish this?

**Comment by paolosanchi** [comment]
@daleharvey my npm account is paolo.sanchi

**Comment by paolosanchi** [comment]
@daleharvey ping :)
I'm ready to publish (still getting 403)

**Comment by daleharvey** [comment]
Hey sorry for the delay, you are added now, thanks :)

**Comment by paolosanchi** [comment]
This is my first npm publish. Hope it worked :D
