### ISSUE TITLE
Dependencies out of date

### ISSUE THREAD

**Issue by jpike88** [pouchdb-community/pouchdb-adapter-cordova-sqlite#96]
@nolanlawson there's a library being pulled in by this version that pulls in pouchdb-binary-utils@6.4.3 which then pulls in buffer-from@0.1.1, which also pulls this in crazy tree of dependencies. The latest buffer-from has no dependencies, but pouchdb-binary-utils is not up to date. I have a screenshot of npm ls (it goes down like another screens worth).

Relevant post showing many of these libraries are unnecessary anyway:

https://github.com/Xotic750/to-string-tag-x/issues/4#issuecomment-492941514

Would appreciate if this could be updated, or be given a pathway forward here for making a PR you'd consider

Thanks
![Screen Shot 2019-05-20 at 2 01 11 pm](https://user-images.githubusercontent.com/9585787/58002135-be58f800-7b07-11e9-8adb-ba1b8ce4e17f.png)

**Comment by paolosanchi** [comment]
do you mean that is enough to update the pouchdb-adapter-websql-core to 7.0.0? can you please test if it causes any problem? I have few time to do it now.

**Comment by jpike88** [comment]
I can certainly do that, I give it a test over the next day

**Comment by jpike88** [comment]
@paolosanchi I decided to just try it now actually... works fine on iOS simulator and device

**Comment by paolosanchi** [comment]
Ok. I'll update it. Did you try the find() feature? It gave some issues in the recent past

**Comment by jpike88** [comment]
Find also seems to work alright, but I don't use it in production and haven't stress tested it. I've already been using PouchDB 7.0.0 for ages now, all seems ok

**Comment by paolosanchi** [comment]
Updated

**Comment by jpike88** [comment]
legend, thanks
