### ISSUE TITLE
Console error message when using Capacitor

### ISSUE THREAD

**Issue by ibrahimawadhamid** [pouchdb-community/pouchdb-adapter-cordova-sqlite#99]
An error message appears in the console when using Capacitor:
<img width="412" alt="Screen Shot 2021-02-15 at 12 21 08 PM" src="https://user-images.githubusercontent.com/44545113/107934436-b7834180-6f88-11eb-8fd8-d5ddff86829e.png">

The error message is harmless and everything is working fine.
After code inspection, I found out that the checking for Capacitor doesn't exist, so I created a pull request #98  adding the checking and fixing the issue.
@paolosanchi

**Comment by paolosanchi** [comment]
Closing due to accept
